[package]
name = "hyper-webgl"
version = "0.1.0"
authors = ["XP2"]
description = "Hyperbolic visualisation in WebGl"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.89"
